# Generated by Django 4.1.1 on 2022-10-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phn_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('publish_date', models.CharField(max_length=255)),
                ('book_copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book_lend_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('stud_name', models.CharField(max_length=255)),
                ('book_taken_date', models.CharField(max_length=255)),
                ('book_return_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='fine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('stud_name', models.CharField(max_length=255)),
                ('book_taken_date', models.CharField(max_length=255)),
                ('book_return_date', models.CharField(max_length=255)),
                ('fine_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phn_no', models.IntegerField()),
            ],
        ),
    ]
