# Generated by Django 4.1.1 on 2022-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_remove_student_details_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='user_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
