# Generated by Django 4.1.1 on 2022-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_student_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='user_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
