# Generated by Django 4.1.1 on 2022-11-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_alter_student_details_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='user_id',
        ),
    ]
