# Generated by Django 4.1.1 on 2022-11-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0009_rename_email_emails_rename_email_emails_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emails',
        ),
    ]
