# Generated by Django 4.1.1 on 2022-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_delete_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
